name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t dockliver/my_interactive_website:latest .

      - name: Push Docker Image to DockerHub
        run: docker push dockliver/my_interactive_website:latest


      # Run build script (if applicable)
      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes first
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Only run deployment if tests pass
    if: github.ref == 'refs/heads/main'  # Deploy only on main branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

