name: CI/CD Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (example for a Node.js project; adjust as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or whichever version you need

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run build script (if applicable)
      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes first
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Only run deployment if tests pass
    if: github.ref == 'refs/heads/main'  # Deploy only on main branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Example: Deploy using Docker (update this section for your deployment needs)
      - name: Build Docker image
        run: docker build -t dockliver/my_interactive_website:latest .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push dockliver/my_interactive_website:latest
