name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Dockerfile Dynamically
        run: |
          echo "FROM node:18" >> Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY package.json package-lock.json ./" >> Dockerfile
          echo "RUN npm install" >> Dockerfile
          echo "COPY . ." >> Dockerfile
          echo "EXPOSE 3000" >> Dockerfile
          echo "CMD [\"npm\", \"start\"]" >> Dockerfile

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t dockliver/my_interactive_website:latest .

      - name: Push Docker Image to DockerHub
        run: docker push dockliver/my_interactive_website:latest
